[2022-12-15T06:07:21.287+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-12-15T00:07:10.585416+00:00 [queued]>
[2022-12-15T06:07:21.301+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: twitter_etl.extract scheduled__2022-12-15T00:07:10.585416+00:00 [queued]>
[2022-12-15T06:07:21.302+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-15T06:07:21.302+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-15T06:07:21.302+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-15T06:07:21.320+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): extract> on 2022-12-15 00:07:10.585416+00:00
[2022-12-15T06:07:21.326+0000] {standard_task_runner.py:55} INFO - Started process 173 to run task
[2022-12-15T06:07:21.329+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'extract', 'scheduled__2022-12-15T00:07:10.585416+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmphh3saatv']
[2022-12-15T06:07:21.329+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask extract
[2022-12-15T06:07:21.459+0000] {task_command.py:376} INFO - Running <TaskInstance: twitter_etl.extract scheduled__2022-12-15T00:07:10.585416+00:00 [running]> on host 894f95b970dd
[2022-12-15T06:07:21.528+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lambobr1994@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T00:07:10.585416+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T00:07:10.585416+00:00
[2022-12-15T06:07:21.529+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-15T06:07:21.530+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/python_scripts/start_dms.py']
[2022-12-15T06:07:21.541+0000] {subprocess.py:86} INFO - Output:
[2022-12-15T06:07:22.286+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-15T06:07:22.287+0000] {subprocess.py:93} INFO -   File "/opt/***/python_scripts/start_dms.py", line 7, in <module>
[2022-12-15T06:07:22.287+0000] {subprocess.py:93} INFO -     with open(r'C:\Users\lambo\PycharmProjects\pythonProject\ETL_projects\aws-offsec\dms_config.json') as file:
[2022-12-15T06:07:22.287+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lambo\\PycharmProjects\\pythonProject\\ETL_projects\\aws-offsec\\dms_config.json'
[2022-12-15T06:07:22.338+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-15T06:07:22.347+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-15T06:07:22.351+0000] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_etl, task_id=extract, execution_date=20221215T000710, start_date=20221215T060721, end_date=20221215T060722
[2022-12-15T06:07:22.368+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 9 for task extract (Bash command failed. The command returned a non-zero exit code 1.; 173)
[2022-12-15T06:07:22.384+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-15T06:07:22.404+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
